# Generated by Django 5.2.5 on 2025-08-09 20:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(help_text='Ürünün tam adını giriniz', max_length=200, verbose_name='Ürün Adı')),
                ('aciklama', models.TextField(help_text='Ürün hakkında detaylı bilgi', verbose_name='Açıklama')),
                ('fiyat', models.DecimalField(decimal_places=2, help_text='Ürün fiyatı (TL)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Fiyat')),
                ('stok_adedi', models.PositiveIntegerField(default=0, help_text='Mevcut stok miktarı', verbose_name='Stok Adedi')),
                ('kategori', models.CharField(blank=True, help_text='Ürün kategorisi', max_length=100, verbose_name='Kategori')),
                ('resim_url', models.URLField(blank=True, help_text='Ürün resim bağlantısı', null=True, verbose_name='Resim URL')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Siparişin toplam tutarı (TL)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Toplam Tutar')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('hazirlaniyor', 'Hazırlanıyor'), ('kargoda', 'Kargoda'), ('teslim_edildi', 'Teslim Edildi'), ('iptal_edildi', 'İptal Edildi')], default='beklemede', max_length=20, verbose_name='Sipariş Durumu')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparisler', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-siparis_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SiparisKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1, help_text='Sipariş edilen ürün adedi', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Adet')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, help_text='Sipariş anındaki ürün fiyatı (TL)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Birim Fiyat')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='onep.siparis', verbose_name='Sipariş')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onep.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.PositiveIntegerField(choices=[(1, '1 - Çok Kötü'), (2, '2 - Kötü'), (3, '3 - Orta'), (4, '4 - İyi'), (5, '5 - Mükemmel')], help_text='1-5 arası puan veriniz', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puan')),
                ('yorum_metni', models.TextField(help_text='Ürün hakkındaki görüşlerinizi paylaşın', verbose_name='Yorum')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='onep.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['-tarih'],
                'unique_together': {('urun', 'kullanici')},
            },
        ),
    ]
