"""
Django settings for ONEP project.

Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
import os
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-onep-e-commerce-platform-development-key-2025')

# SECURITY WARNING: don't run with debug turned on in production! - OPTIMIZE EDİLDİ
DEBUG = config('DEBUG', default=False, cast=bool)

# Production Debug Environment Check (OPTIMIZE EDİLDİ)
import os
if DEBUG:
    print(f"🔧 ONEP DEBUG: Environment check")
    print(f"🔧 DATABASE_URL exists: {'DATABASE_URL' in os.environ}")
    print(f"🔧 SECRET_KEY from env: {'SECRET_KEY' in os.environ}")
    print(f"🔧 Current working directory: {os.getcwd()}")

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# Production Security Settings (OPTIMIZE EDİLDİ)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 yıl
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'onep',  # ONEP uygulamamız
]

# Cache framework ayarları (PERFORMANCE BOOST)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'onep-cache',
        'TIMEOUT': 300,  # 5 dakika önbellek
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Maksimum önbellek girişi
            'CULL_FREQUENCY': 3,  # Her 3 seferinde bir fazlalık girdileri temizle
        }
    }
}

# Site genelinde önbellek
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 600  # 10 dakika önbellek
CACHE_MIDDLEWARE_KEY_PREFIX = 'onep'

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',  # En başa ekle
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'onep.middleware.CartNoCacheMiddleware',  # Sepet cache bypass middleware'i
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',  # En sona ekle
]

ROOT_URLCONF = 'ONEP_ORG.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'onep' / 'templates'],
        'APP_DIRS': False,  # loaders kullanırken False olmalı
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'onep.context_processors.cart_context',
            ],
            # Template önbelleği (PERFORMANCE BOOST)
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = 'ONEP_ORG.wsgi.application'


# Database - PostgreSQL bağlantı yapılandırması (OPTIMIZE EDİLDİ)
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Önce dj_database_url ile temel bağlantıyı alın
db_config = dj_database_url.config(
    default="postgresql://postgres:Selam.235689.@127.0.0.1:5432/onep_db",
    conn_max_age=int(os.environ.get('DATABASE_CONN_MAX_AGE', 600)),
    conn_health_checks=True,
)

# Sonra PostgreSQL özel ayarlarını ekleyin
if db_config:
    # PostgreSQL options'ı ekliyoruz
    db_config['OPTIONS'] = {
        'connect_timeout': 5,
        'keepalives': 1,
        'keepalives_idle': 30,
        'keepalives_interval': 5,
        'keepalives_count': 5,
    }

DATABASES = {
    'default': db_config
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization - Türkçe dil ayarları
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static files (CSS, JavaScript, Images) - OPTIMIZE EDİLDİ
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for compressed static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session configuration for cart management (OPTIMIZE EDİLDİ - WORKER SYNC)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Database için zorunlu
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # 1 gün
SESSION_SAVE_EVERY_REQUEST = True  # Her istekte session'ı kaydet (WORKER SYNC)
SESSION_COOKIE_SECURE = not DEBUG  # Production'da True
SESSION_COOKIE_HTTPONLY = True  # JavaScript erişimine kapalı

# Login/Logout redirect URLs
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Logging Configuration (OPTIMIZE EDİLDİ)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'] if DEBUG else ['file'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['console'] if DEBUG else [],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'onep': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
LOGIN_URL = '/login/'

# Security settings for production
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)

# Admin paneli için Türkçe ayarlar
ADMIN_SITE_HEADER = 'ONEP Admin Paneli'
ADMIN_SITE_TITLE = 'ONEP Yönetimi'
ADMIN_INDEX_TITLE = 'ONEP E-Ticaret Platformu Yönetimi'
